// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitoWeb.Data;

#nullable disable

namespace SitoWeb.Migrations
{
    [DbContext(typeof(NBADbContext))]
    [Migration("20250301100504_init4")]
    partial class init4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SitoWeb.Model.Giocatore", b =>
                {
                    b.Property<int>("GiocatoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GiocatoreId"));

                    b.Property<int>("Altezza")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("date");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<string>("GiocatoreName")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazionalita")
                        .HasColumnType("longtext");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Ruolo")
                        .HasColumnType("longtext");

                    b.Property<string>("SquadraId")
                        .HasColumnType("longtext");

                    b.Property<int?>("SquadraId1")
                        .HasColumnType("int");

                    b.HasKey("GiocatoreId");

                    b.HasIndex("SquadraId1");

                    b.ToTable("Giocatori");
                });

            modelBuilder.Entity("SitoWeb.Model.Squadra", b =>
                {
                    b.Property<int>("SquadraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SquadraId"));

                    b.Property<int>("AnnoFondazione")
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Stadio")
                        .HasColumnType("longtext");

                    b.HasKey("SquadraId");

                    b.ToTable("Squadre");
                });

            modelBuilder.Entity("SitoWeb.Model.Giocatore", b =>
                {
                    b.HasOne("SitoWeb.Model.Squadra", "Squadra")
                        .WithMany("Giocatori")
                        .HasForeignKey("SquadraId1");

                    b.Navigation("Squadra");
                });

            modelBuilder.Entity("SitoWeb.Model.Squadra", b =>
                {
                    b.Navigation("Giocatori");
                });
#pragma warning restore 612, 618
        }
    }
}
